# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: Test1
  displayName: Test Hello World
  jobs:
  - job: Test1
    displayName: Test Hello World
    pool:
      vmImage: $(vmImageName)
    steps:
    # Record build start
    - script: echo "Hello World"